# Generated by Django 3.2 on 2021-05-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210501_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
