# Generated by Django 3.2 on 2021-05-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210505_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'active'), ('s', 'sold'), ('d', 'deleted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='listings_on_category', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.URLField(),
        ),
    ]
