# Generated by Django 3.2 on 2021-05-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
